services:
  bili_tool_web:
    image: ghcr.io/raywangqvq/bili_tool_web
    container_name: bili_tool_web
    restart: unless-stopped
    tty: true
    volumes:
      - ./Logs:/app/Logs
      - ./config:/app/config
    ports:
      - "22330:8080"
    environment:
      TZ: "Asia/Shanghai"
      DailyTaskConfig__Cron: "0 0 15 * * ?"
