name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile.minimal --tag bilibilitoolpro:latest

      - name: Test Docker image
        run: |
          echo "Docker build completed successfully!"
          docker images | grep bilibilitoolpro 